volumes:
  postgres_data:
  clickhouse_data:

services:
  postgres:
    image: 'postgres:17'

    environment:
      POSTGRES_DB: '$POSTGRES_DB'
      POSTGRES_USER: '$POSTGRES_USER'
      POSTGRES_PASSWORD: '$POSTGRES_PASSWORD'
    volumes:
      - './scripts/postgres:/docker-entrypoint-initdb.d:ro'
      - './source:/source:ro'
      - 'postgres_data:/var/lib/postgresql/data'

  clickhouse:
    image: 'clickhouse/clickhouse-server:$CLICKHOUSE_TAG'

    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: '1'
      CLICKHOUSE_DB: '$CLICKHOUSE_DB'
      CLICKHOUSE_USER: '$CLICKHOUSE_USER'
      CLICKHOUSE_PASSWORD: '$CLICKHOUSE_PASSWORD'
    volumes:
      - './scripts/clickhouse:/docker-entrypoint-initdb.d:ro'
      - './source:/source:ro'
      - 'clickhouse_data:/var/lib/clickhouse'

    ports:
      - '${CLICKHOUSE_WEBUI_PORT:-8123}:8123'

    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  trino:
    image: 'trinodb/trino:$TRINO_TAG'

    volumes:
      - './etc/trino/catalog:/etc/trino/catalog:ro'
      - './scripts/trino:/scripts:ro'

    ports:
      - '${TRINO_WEBUI_PORT:-8080}:8080'

    depends_on:
      - 'postgres'
      - 'clickhouse'
